### ISSUE TITLE
Is that a corgi on your profile?

### ISSUE THREAD

**Issue by willklein** [alanbsmith/alanbsmith#1]
Because I see a corgi and I need confirmation. I humbly await your response to this query.

**Comment by willklein** [comment]
This is how open source works, right?

**Comment by alanbsmith** [comment]
This is exactly how open source works.

**Comment by alanbsmith** [comment]
Thank you for raising this issue, @willklein. I updated the alt text to specify the doggo's presumed breed and am closing this issue.
